#spring
server:
  port: 8080
  tomcat:
    max-threads: 1000
    max-connections: 2000

spring:
  application:
    name: mickey-example-web
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  profiles:
    active: @spring.profiles.active@
  main:
    allow-bean-definition-overriding: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB #总体文件最大
